"""empty message

Revision ID: c4338c285145
Revises: a96afb1ffdc5
Create Date: 2025-01-03 18:03:44.973921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4338c285145'
down_revision = 'a96afb1ffdc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('result', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'result')
    # ### end Alembic commands ###
